name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    #use vm from github
    runs-on: ubuntu-latest
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres:16.3
          # Provide the password for postgres
          env:
            POSTGRES_USER: sam
            POSTGRES_PASSWORD: test
            POSTGRES_DB: customer
          ports:
            -"5332:5432"
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
        #checkout the code to workflow
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'maven'
      - name: Build and run Integration Test with Maven
        run: mvn -ntp -B verify